- platform: mqtt
  name: "SkyHD"
  state_topic: "SkyHD/Status"
  value_template: >-
    {{ value }}
  command_topic: "SkyHD/Power"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  retain: false