- platform: mjpeg
  mjpeg_url: http://192.168.0.23:8082
  name: 'Front'
- platform: mjpeg
  mjpeg_url: http://192.168.0.23:8081
  name: 'Side'
- platform: mjpeg
  mjpeg_url: http://192.168.0.23:8083
  name: 'Back'
# - platform: mjpeg
  # mjpeg_url: http://192.168.0.23:8081
  # name: 'FrontHD'
- platform: mjpeg
  mjpeg_url: http://192.168.0.23:8085
  name: 'Living Room'
- platform: mjpeg
  mjpeg_url: http://192.168.0.23:8084
  name: 'Kitchen'
- platform: mjpeg
  mjpeg_url: http://192.168.0.23:8086
  name: 'Garage'
- platform: mjpeg
  mjpeg_url: http://192.168.0.23:8087
  name: 'Conservatory'
- platform: mjpeg
  mjpeg_url: http://192.168.0.23:8088
  name: 'Doorbell'
- platform: mjpeg
  mjpeg_url: http://192.168.0.23:8089
  name: 'Fire7'

# - platform: ffmpeg
  # input: !secret cctv_url_front
  # name: FrontHD
# - platform: ffmpeg
  # input: !secret cctv_url_side
  # name: Side
# - platform: ffmpeg
  # input: !secret cctv_url_back
  # name: Back

- platform: generic
  still_image_url: !secret xiaomi_vacuum_map
  name: Vacuum Map
  content_type: image/png

- platform: generic
  name: 'Lolo'
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ state_attr("device_tracker.ha_lolos_iphone","latitude") }},{{ state_attr("device_tracker.ha_lolos_iphone","longitude") }}&zoom=15&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:L%7C{{ state_attr("device_tracker.ha_lolos_iphone","latitude") }},{{ state_attr("device_tracker.ha_lolos_iphone","longitude") }}&markers=color:red%7Clabel:D%7C{{ state_attr("device_tracker.ha_div_iphone","latitude") }},{{ state_attr("device_tracker.ha_div_iphone","longitude") }}
  limit_refetch_to_url_change: true
- platform: generic
  name: 'Div'
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ state_attr("device_tracker.ha_div_iphone","latitude") }},{{ state_attr("device_tracker.ha_div_iphone","longitude") }}&zoom=15&size=500x500&maptype=roadmap&markers=color:red%7Clabel:D%7C{{ state_attr("device_tracker.ha_div_iphone","latitude") }},{{ state_attr("device_tracker.ha_div_iphone","longitude") }}&markers=color:blue%7Clabel:L%7C{{ state_attr("device_tracker.ha_lolos_iphone","latitude") }},{{ state_attr("device_tracker.ha_lolos_iphone","longitude") }}
  limit_refetch_to_url_change: true
- platform: generic
  name: YrForecastCrawley
  still_image_url: https://www.yr.no/place/United_Kingdom/England/Maidenbower/meteogram.svg
  content_type: 'image/svg+xml'
- platform: generic
  name: YrForecastWeybridge
  still_image_url: https://www.yr.no/place/United_Kingdom/England/Weybridge/meteogram.svg
  content_type: 'image/svg+xml'
- platform: generic
  name: chromecast_radio_pic
  still_image_url: >
    {% set my_speaker = "media_player."+states("input_select.chromecast_radio_speakers")|lower %}
    {% if is_state(my_speaker,"playing") and is_state("binary_sensor.radio_is_streaming", "on")%}
    {% if is_state("input_select.chromecast_radio_station", "RTL2") %} {{states("sensor.rtl2_pic")}}
    {% elif is_state("input_select.chromecast_radio_station", "Absolute Radio") %} {{states("sensor.absolute_radio_pic")}}
    {% elif is_state("input_select.chromecast_radio_station", "Absolute Radio Classic Rock") %} {{states("sensor.absolute_radio_CR_pic")}}
    {% elif is_state("input_select.chromecast_radio_station", "Hit West") %} https://upload.wikimedia.org/wikipedia/fr/b/bd/HitWestLogo.jpg
    {% elif is_state("input_select.chromecast_radio_station", "HA Podcast") %} https://secureimg.stitcher.com/feedimageswide/480x270_176113.jpg
    {% elif is_state("input_select.chromecast_radio_station", "IoT Podcast") %} https://is1-ssl.mzstatic.com/image/thumb/Music62/v4/b3/d6/64/b3d664ab-0560-f24d-2379-d01142267f94/source/1200x630bb.jpg
    {% elif is_state("input_select.chromecast_radio_station", "Chill") %} {{states("sensor.chill_pic")}}
    {% elif is_state("input_select.chromecast_radio_station", "Navtarang") %} https://static-media.streema.com/media/cache/61/a2/61a237fb6851e34614c55420b3e11a62.jpg
    {% elif is_state("input_select.chromecast_radio_station", "Radio Fiji Two") %} http://player.streamguys.com/fbc/sgplayer/include/assets/img/RF2.png
    {% elif is_state("input_select.chromecast_radio_station", "Custom Station") %} https://www.holyscripturesandisrael.com/images/radio/radio-icon.png
    {% endif %}
    {%else%}http://192.168.0.24/Select_Radio.png
    {%endif%}
    
# - name: Fire7
  # platform: generic
  # still_image_url: !secret fire7camshot
  
  
- platform: generic
  name: FrontHD
  still_image_url: !secret xiaomi_vacuum_map
  stream_source: !secret cctv_url_front
  
  

- platform: generic
  name: Doorbell_Pic
  still_image_url: http://192.168.0.24:8123/local/CCTV_Snapshots/Doorbell.jpg



- platform: generic
  name: Grafana Lolo Weight
  still_image_url: http://192.168.0.24:3000/render/d-solo/ItrU5gHik/ha-dashboard?orgId=1&panelId=6&width=1000&height=500&tz=Europe%2FLondon
  username: !secret grafana_user
  password: !secret grafana_password

- platform: generic
  name: Grafana CPU RAM
  still_image_url: http://192.168.0.24:3000/render/d-solo/ItrU5gHik/ha-dashboard?orgId=1&panelId=8&width=1000&height=500&tz=Europe%2FLondon
  username: !secret grafana_user
  password: !secret grafana_password