title: nesthub

resources:

custom_header:
  compact_mode: true
  background: 'rgba(155, 155, 155, 0.25)'
  show_tabs: 0
  kiosk_mode: true
  exceptions:
    - conditions:
        user: Laurent, Divashni
      config:
        show_tabs: '0 to 50'
        kiosk_mode: false
        # button_text:
          # options: '{{ hours24 }}:{{ minutesLZ }}  ⁞'

preload_cards:
  - 'custom:canvas-gauge-card'


views:
  - !include /config/lovelace_views/nest_hub.yaml
  # - !include /config/lovelace_views/test.yaml