title: Automation
#background: url("/local/calendar-check.png") fixed
icon: mdi:calendar-check
cards:
  - type: entities
    show_header_toggle: false
    entities:
      - type: custom:auto-entities
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: All Automations
          open: false
        filter:
          include:
            - entity_id: "automation.*"
        sort:
          method: 'name'

  - type: 'custom:auto-entities'
    card:
      type: 'custom:home-feed-card'
      title: Automations
      show_empty: true
      more_info_on_tap: true
      max_item_count: 99
    filter:
      include:
        - domain: automation