- platform: template
  sensors:
    # aloe_vera_battery2:
      # friendly_name: Aloe Vera Battery
      # unit_of_measurement: '%'
      # value_template: '{{states("sensor.aloe_vera_battery") | int}}'
      # device_class: battery
    # fire7_battery:
      # friendly_name: Fire7 Battery
      # unit_of_measurement: '%'
      # value_template: '{{state_attr("binary_sensor.fire7_motion", "battery_level") | int}}'
      # device_class: battery
    ground_floor_smoke_detector_battery:
      friendly_name: Ground Floor Smoke Detector Battery
      unit_of_measurement: '%'
      value_template: '{{state_attr("binary_sensor.ground_floor_smoke_detector", "battery_level") | int}}'
      device_class: battery
    first_floor_smoke_detector_battery:
      friendly_name: First Floor Smoke Detector Battery
      unit_of_measurement: '%'
      value_template: '{{state_attr("binary_sensor.first_floor_smoke_detector", "battery_level") | int}}'
      device_class: battery
    blue_room_big_window_battery:
      friendly_name: Blue Room Big Window Battery
      unit_of_measurement: '%'
      value_template: '{{state_attr("binary_sensor.blue_room_big_window", "battery_level") | int}}'
      device_class: battery
    blue_room_small_window_battery:
      friendly_name: Blue Room Small Window Door
      unit_of_measurement: '%'
      value_template: '{{state_attr("binary_sensor.blue_room_small_window", "battery_level") | int}}'
      device_class: battery
    conservatory_sklylight_right_battery:
      friendly_name: Conservatory Skyghlight Right Battery
      unit_of_measurement: '%'
      value_template: '{{state_attr("binary_sensor.conservatory_skylight_right", "battery_level") | int}}'
      device_class: battery
    conservatory_single_door_battery:
      friendly_name: Conservatory Single Door Battery
      unit_of_measurement: '%'
      value_template: '{{state_attr("binary_sensor.conservatory_single_door", "battery_level") | int}}'
      device_class: battery
    conservatory_double_door_battery:
      friendly_name: Conservatory Double Door Battery
      unit_of_measurement: '%'
      value_template: '{{state_attr("binary_sensor.conservatory_double_door", "battery_level") | int}}'
      device_class: battery
    kiaan_big_window_battery:
      friendly_name: Kiaan Big Window Battery
      unit_of_measurement: '%'
      value_template: '{{state_attr("binary_sensor.kiaan_big_window", "battery_level") | int}}'
      device_class: battery
    kiaan_small_window_battery:
      friendly_name: Kiaan Small Window Door
      unit_of_measurement: '%'
      value_template: '{{state_attr("binary_sensor.kiaan_small_window", "battery_level") | int}}'
      device_class: battery
    kitchen_window_battery:
      friendly_name: Kitchen Window Door
      unit_of_measurement: '%'
      value_template: '{{state_attr("binary_sensor.kitchen_window", "battery_level") | int}}'
      device_class: battery
    living_room_left_window_battery:
      friendly_name: Living Room Left Window Battery
      unit_of_measurement: '%'
      value_template: '{{state_attr("binary_sensor.living_room_right_small_window", "battery_level") | int}}'
      device_class: battery
    living_room_right_window_battery:
      friendly_name: Living Room Right Window Battery
      unit_of_measurement: '%'
      value_template: '{{state_attr("binary_sensor.living_room_right_big_window", "battery_level") | int}}'
      device_class: battery
    kitchen_freezer_temperature_battery:
      friendly_name: Kitchen Freezer Temperature Battery
      unit_of_measurement: '%'
      value_template: '{{state_attr("sensor.kitchen_freezer_humidity", "battery_level") | int}}'
      device_class: battery
    garage_freezer_temperature_battery:
      friendly_name: Garage Freezer Temperature Battery
      unit_of_measurement: '%'
      value_template: '{{state_attr("sensor.garage_freezer_humidity", "battery_level") | int}}'
      device_class: battery
    # master_bedroom_temperature_battery:
      # friendly_name: Master Bedroom Temperature Battery
      # unit_of_measurement: '%'
      # value_template: '{{state_attr("sensor.master_bedroom_hygro", "battery_level") | int}}'
      # device_class: battery
    master_bedroom_left_window_battery:
      friendly_name: Master Bedroom Left Window Battery
      unit_of_measurement: '%'
      value_template: '{{state_attr("binary_sensor.master_bedroom_left_big_window", "battery_level") | int}}'
      device_class: battery
    bathroom_window_battery:
      friendly_name: Bathroom Window Battery
      unit_of_measurement: '%'
      value_template: '{{state_attr("binary_sensor.bathroom_window", "battery_level") | int}}'
      device_class: battery
    cloakroom_window_battery:
      friendly_name: Cloakroom Window Battery
      unit_of_measurement: '%'
      value_template: '{{state_attr("binary_sensor.cloakroom_window", "battery_level") | int}}'
      device_class: battery
    # loft_temperature_battery:
      # friendly_name: Loft Temperature Battery
      # unit_of_measurement: '%'
      # value_template: '{% if state_attr("sensor.loft_temperature", "Battery numeric")|int == 9 %}90{% else %}9{% endif %}'
      # device_class: battery
    main_door_battery:
      friendly_name: Main Door Battery
      unit_of_measurement: '%'
      value_template: '{{state_attr("binary_sensor.main_door", "battery_level") | int}}'
      device_class: battery
    # upstairs_temperature_battery:
      # friendly_name: Upstairs Temperature Battery
      # unit_of_measurement: '%'
      # value_template: '{% if state_attr("sensor.upstairs_temperature", "Battery numeric")|int == 9 %}90{% else %}9{% endif %}'
      # device_class: battery
