- platform: mqtt
  name: "PIR Living Room Back"
  state_topic: "RPi/PIRLivingRoomBack"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion

- platform: mqtt
  name: "PIR Living Room Front"
  state_topic: "RPi/PIRLivingRoomFront"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion

- platform: mqtt
  name: "PIR Kitchen"
  state_topic: "RPi/PIRKitchen"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion

- platform: mqtt
  name: "PIR Conservatory"
  state_topic: "RPi/PIRConservatory"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion

- platform: mqtt
  name: "PIR Staircase"
  state_topic: "RPi/PIRStaircase"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion

- platform: mqtt
  name: "PhotoResistor"
  state_topic: "RPi/PhotoResistor"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: light

- platform: mqtt
  name: "Door Lock"
  state_topic: "RPi/DoorLock"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: safety

