- alias: Lights - All Lights Off
  initial_state: true
  trigger:
    - platform: state
      entity_id: group.pirs
      to: 'off'
      for:
        minutes: 3
  condition:
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: state
      entity_id: media_player.panasonic_viera_tv
      state: 'off'
  action:
  - service: light.turn_off
    data:
      entity_id: group.interior_lights
  - service: switch.turn_off
    data:
      entity_id: switch.kitchen_tv
  - service: input_boolean.turn_off
    entity_id: media_player.panasonic_viera_tv
  - service: input_boolean.turn_off
    entity_id: media_player.onkyo_tx_nr656
  - delay: 00:00:01
  - service: light.turn_off
    data:
      entity_id: light.wled_conservatory
  - delay: 00:00:01
  - service: light.turn_off
    data:
      entity_id: light.wled_conservatory
  - service: light.turn_off
    data:
      entity_id: group.xmas


- alias: Lights - All Lights Off - Sunrise
  initial_state: true
  trigger:
    - platform: state
      entity_id: sun.sun
      to: 'above_horizon'
      for:
        hours: 1
    - platform: state
      entity_id: sun.sun
      to: 'above_horizon'
      for:
        hours: 2
    - platform: state
      entity_id: sun.sun
      to: 'above_horizon'
      for:
        hours: 3
  action:
  - service: cover.open_cover
    data:
      entity_id:
        - cover.kitchen_blinds
        - cover.livingroom_blinds
  - service: light.turn_off
    data:
      entity_id: group.interior_lights
  - delay: 00:00:01
  - service: light.turn_off
    data:
      entity_id: light.wled_conservatory
  - delay: 00:00:01
  - service: light.turn_off
    data:
      entity_id: light.wled_conservatory

