- alias: Bathroom - Turn Fan On When R% > 75%
  id: bathroom_-_turn_fan_on_when_r_over_75
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.bathroom_humidity
  condition:
    - condition: or
      conditions:
        - condition: template
          value_template: '{{ states("sensor.bathroom_humidity") | int > 75 and states("sensor.season") != "autumn"}}'
        - condition: template
          value_template: '{{ states("sensor.bathroom_humidity") | int > 80 and states("sensor.season") == "autumn"}}'
    - condition: state
      entity_id: switch.bathroom_fan
      state: 'off'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.bathroom_fan

- alias: Bathroom - Turn Fan Off When R% < 75%
  id: bathroom_-_turn_fan_off_when_r_under_75
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.bathroom_humidity
      below: 75
      for:
        minutes: 20
    - platform: state
      entity_id: switch.bathroom_fan
      to: 'on'
      for:
        minutes: 59
  condition:
    - condition: state
      entity_id: switch.bathroom_fan
      state: 'on'
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.bathroom_fan

- alias: Bathroom - Toggle Fan From Hygro Sensor
  initial_state: false
  trigger:
    - platform: state
      entity_id: sensor.bathroom_fan_switch_toggle
  action:
  - condition: template
    value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("automation.bathroom_toggle_fan_from_hygro_sensor", "last_triggered") | default(0)) | int <= 5)}}'
  - service: switch.toggle
    data:
      entity_id: switch.bathroom_fan