- alias: Doorbell - Doorbell Notification
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.doorbell_ring
      to: 'on'
  action:
  - service: scene.create
    data_template:
      scene_id: pre_doorbell_state
      snapshot_entities:
        - light.living_room_main
        - media_player.google_home_minis
        - media_player.panasonic_viera_tv
        - media_player.onkyo_tx_nr656
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.google_home_minis
      volume_level: 1
  - service: media_player.play_media
    data:
      entity_id: media_player.google_home_minis
      media_content_id: 'http://192.168.0.24/audio/Doorbell_Tubular_2.mp3'
      media_content_type: 'audio/mp3'
  - service: camera.snapshot
    data:
      entity_id: camera.doorbell
      filename: '/config/www/CCTV_Snapshots/Doorbell.jpg'
  - condition: template
    value_template: '{{ states("binary_sensor.pir_living_room_front")== "on" or states("binary_sensor.pir_living_room_back")== "on" or states("media_player.panasonic_viera_tv")== "on" }}'
  - service: media_player.turn_on
    data:
      entity_id: media_player.viera
  - service: media_player.turn_on
    data:
      entity_id: media_player.panasonic_viera_tv
  - wait_template: '{{ states("media_player.panasonic_viera_tv")== "on" }}'
    timeout: '00:00:05'
  - service: media_player.play_media
    data:
      entity_id: media_player.panasonic_viera_tv
      media_content_id: 'http://192.168.0.23:8088/'
      media_content_type: url
  - service: media_player.volume_mute
    data_template:
      entity_id: media_player.conservatory, media_player.house, media_player.kitchen, media_player.onkyo_tx_nr656_2
      is_volume_muted: true
  - delay: 00:00:30
  - service: media_player.turn_off
    data:
      entity_id: media_player.viera
  - service: scene.turn_on
    data:
      entity_id: scene.pre_doorbell_state








- alias: Doorbell - Reboot When Video Feed Lost
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - alert.cctv_doorbell_video_feed_lost
      to: 'on'
  condition:
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("automation.doorbell_reboot_when_video_feed_lost", "last_triggered") | default(0)) | int > 300)}}'
  action:
    - service: shell_command.reboot_doorbell