- alias: Fire Stick 4K - Turn Movies on when Netflix or Prime is Playing
  initial_state: true
  trigger:
    - platform: state
      entity_id: media_player.fire_stick_4k
      to: 'playing'
      for:
        seconds: 5
    - platform: state
      entity_id: media_player.fire_stick_4k
  condition:
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: template
      value_template: >-
        {{
        state_attr("media_player.fire_stick_4k","app_name") == "Netflix"
        or state_attr("media_player.fire_stick_4k","app_name") == "com.apple.atve.amazon.appletv"
        or state_attr("media_player.fire_stick_4k","app_name") == "Plex"
        or state_attr("media_player.fire_stick_4k","app_name") ==  "com.disney.disneyplus"
        or state_attr("media_player.fire_stick_4k","app_name") == "Amazon Video"
        }}
    - condition: state
      entity_id: binary_sensor.dark
      state: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.movies

- alias: Fire Stick 4K - Dim Lights when Kodi, Netflix or Prime is Paused
  initial_state: true
  trigger:
    - platform: state
      entity_id: media_player.fire_stick_4k
      to: 'paused'
  condition:
    - condition: state
      entity_id: input_boolean.movies
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.living_room_main
      brightness: 11

- alias: Fire Stick 4K - Turn Lights Off when Kodi, Netflix or Prime is Unpaused
  initial_state: true
  trigger:
    - platform: state
      entity_id: media_player.fire_stick_4k
      to: 'playing'
  condition:
    - condition: state
      entity_id: input_boolean.movies
      state: 'on'
  action:
  - service: light.turn_off
    data:
      entity_id: light.living_room_main