- alias: Nest Hub - Start Cast
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: '/10'
      seconds: 0
  condition:
    - condition: template
      value_template: '{{now().hour >= 19 and now().hour < 24 }}'
    - condition: template
      value_template: '{{ states("person.laurent") == "home"}}'
    - condition: template
      value_template: '{{ states("media_player.master_bedroom_display") != "playing"}}'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.master_bedroom_display
        volume_level: 0
    - service: media_player.turn_on
      data:
        entity_id: media_player.master_bedroom_display
    - wait_template: '{{ states("media_player.master_bedroom_display") != "off"}}'
      timeout: '00:00:05'
    - service: cast.show_lovelace_view
      data:
        entity_id: media_player.master_bedroom_display
        view_path: nesthub
    - delay: '00:00:05'
    - service: cast.show_lovelace_view
      data:
        dashboard_path: lovelace-nesthub
        entity_id: media_player.master_bedroom_display
        view_path: nesthub
    - delay: '00:00:05'
    - service: cast.show_lovelace_view
      data:
        dashboard_path: lovelace-nesthub
        entity_id: media_player.master_bedroom_display
        view_path: nesthub
