- alias: Lights - Staircase Light On by PIR
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_staircase
      to: 'on'
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
    - platform: state
      entity_id: binary_sensor.photoresistor
      to: 'off'
    - platform: state
      entity_id: sensor.aloe_vera_light_intensity
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.normal
        state: 'on'
      - condition: state
        entity_id: input_boolean.movies
        state: 'on'
    - condition: state
      entity_id: light.staircase
      state: 'off'
    - condition: state
      entity_id: binary_sensor.pir_staircase
      state: 'on'
    - condition: time
      after: '06:00'
      before: '23:00'
    - condition: state
      entity_id: binary_sensor.dark
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.staircase
      brightness: 255
  - service: light.turn_on
    data:
      entity_id: light.staircase_led_strip
      brightness: 255
      rgb_color: [0,128,255]
  - condition: state
    entity_id: input_boolean.xmas
    state: 'on'
  - service: light.turn_on
    data:
      entity_id: light.staircase_led_strip
      brightness: 255
      effect: rainbow


- alias: Lights - Staircase Light Off by PIR
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_staircase
      to: 'off'
  condition:
    - condition: state
      entity_id: light.staircase
      state: 'on'
  action:
  - service: light.turn_off
    data:
      entity_id: light.staircase
  - service: light.turn_off
    data:
      entity_id: light.staircase_led_strip